// <auto-generated />
using System;
using AuctionSystemCore.AuctionSystemCore.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AuctionSystemCore.AuctionSystemCore.Migrations
{
    [DbContext(typeof(auction_systemContext))]
    [Migration("20210515070607_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AuctionSystemCore.AuctionSystemCore.Models.Bids", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("IncrementAmount")
                        .HasColumnName("increment_amount");

                    b.Property<double>("MaxBid")
                        .HasColumnName("max_bid");

                    b.Property<int>("SoldItemId")
                        .HasColumnName("sold_item_id");

                    b.Property<double>("StartBid")
                        .HasColumnName("start_bid");

                    b.Property<int>("UserId")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("SoldItemId");

                    b.HasIndex("UserId");

                    b.ToTable("bids");
                });

            modelBuilder.Entity("AuctionSystemCore.AuctionSystemCore.Models.Events", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("EndTime")
                        .HasColumnName("end_time")
                        .HasColumnType("datetime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasMaxLength(2000)
                        .IsUnicode(false);

                    b.Property<DateTime>("StartTime")
                        .HasColumnName("start_time")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.ToTable("events");
                });

            modelBuilder.Entity("AuctionSystemCore.AuctionSystemCore.Models.SoldItems", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("BasePrice")
                        .HasColumnName("base_price");

                    b.Property<int>("EventId")
                        .HasColumnName("event_id");

                    b.Property<double>("IncrementLimit")
                        .HasColumnName("increment_limit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasMaxLength(2000)
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("sold_items");
                });

            modelBuilder.Entity("AuctionSystemCore.AuctionSystemCore.Models.Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasMaxLength(255)
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("AuctionSystemCore.AuctionSystemCore.Models.Bids", b =>
                {
                    b.HasOne("AuctionSystemCore.AuctionSystemCore.Models.SoldItems", "SoldItem")
                        .WithMany("Bids")
                        .HasForeignKey("SoldItemId")
                        .HasConstraintName("FK__bids__sold_item___2C3393D0");

                    b.HasOne("AuctionSystemCore.AuctionSystemCore.Models.Users", "User")
                        .WithMany("Bids")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__bids__user_id__2B3F6F97");
                });

            modelBuilder.Entity("AuctionSystemCore.AuctionSystemCore.Models.SoldItems", b =>
                {
                    b.HasOne("AuctionSystemCore.AuctionSystemCore.Models.Events", "Event")
                        .WithMany("SoldItems")
                        .HasForeignKey("EventId")
                        .HasConstraintName("FK__sold_item__event__286302EC");
                });
#pragma warning restore 612, 618
        }
    }
}
